FROM ubuntu:22.04

# Install required system packages
RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    curl \
    gzip \
    libbz2-dev \
    zlib1g-dev \
    liblzma-dev \
    libncurses5-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    python3-pip \
    parallel \
    ca-certificates \
    && apt-get clean

# Install HTSlib
RUN wget https://github.com/samtools/htslib/releases/download/1.21/htslib-1.21.tar.bz2 && \
    tar -xjf htslib-1.21.tar.bz2 && \
    cd htslib-1.21 && \
    ./configure --prefix=$PREFIX && \
    make && make install && \
    cd .. && rm -rf htslib-1.21*

# Install BCFtools
RUN wget https://github.com/samtools/bcftools/releases/download/1.21/bcftools-1.21.tar.bz2 && \
    tar -xjf bcftools-1.21.tar.bz2 && \
    cd bcftools-1.21 && \
    ./configure --prefix=$PREFIX && \
    make && make install && \
    cd .. && rm -rf bcftools-1.21*

# Copy your Python script into /usr/bin
COPY bin/* /usr/bin/

# Create a non-root user and switch to it
RUN useradd -m -u 1000 flben

# Make sure the script is executable
RUN chmod +x /usr/bin/*
RUN chown flben:flben /usr/bin/* && chmod +x /usr/bin/*

USER flben

# Install dxpy
RUN pip install dxpy

# Default working directory and shell
WORKDIR /data
SHELL ["/bin/bash", "-c"]
CMD ["bash"]

