# Use the Ensembl VEP release 113.3 image
FROM ensemblorg/ensembl-vep:release_113.3

# Switch to root to install system packages
USER root

# Install necessary system utilities
RUN apt-get update && apt-get install -y \
    build-essential \
    libbz2-dev \
    zlib1g-dev \
    liblzma-dev \
    libncurses5-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    parallel \
    ca-certificates \
    pkg-config \
    libtool \
    git \
    pigz \
    && rm -rf /var/lib/apt/lists/*
    
    
    
# Create a non-root user and switch to it
RUN useradd -m -u 1000 flben


USER flben

# Default working directory and shell
WORKDIR /data
SHELL ["/bin/bash", "-c"]
CMD ["bash"]
