# Base image with bash
FROM ubuntu:22.04

# Avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies for ShortVariants-Annotation
RUN apt-get update && apt-get install -y \
    curl \
    git \
    perl \
    tabix \
    wget \
    unzip \
    gzip \
    tar \
    bcftools \
    samtools \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Set working directory for ShortVariants-Annotation
WORKDIR /ShortVariants-Annotation


# Default command
CMD ["/bin/bash"]
