FROM apache/spark-py:latest

# Switch to root to install system packages
USER root

# Install necessary system utilities
RUN apt-get update && apt-get install -y \
    build-essential \
    libbz2-dev \
    zlib1g-dev \
    liblzma-dev \
    libncurses5-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    parallel \
    ca-certificates \
    pkg-config \
    libtool \
    git \
    pigz \
    && rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip install --no-cache-dir \
    pandas \
    psutil \
    tqdm

# Install htslib
RUN wget https://github.com/samtools/htslib/releases/download/1.21/htslib-1.21.tar.bz2 && \
    tar -xjf htslib-1.21.tar.bz2 && \
    cd htslib-1.21 && \
    ./configure --prefix=$PREFIX && \
    make && make install && \
    cd .. && rm -rf htslib-1.21*
    
    
# Install vcftools
RUN git clone https://github.com/vcftools/vcftools.git /opt/vcftools && \
    cd /opt/vcftools && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install
        

# Copy your Python script into /usr/bin
COPY bin/* /usr/bin/

# Make sure the script is executable
RUN chmod +x /usr/bin/*

# Default working directory and shell
WORKDIR /data
SHELL ["/bin/bash", "-c"]
CMD ["bash"]